[package]
name = "cap_access"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Provide basic capability-based access control to objects"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/cap_access"
documentation = "https://docs.rs/cap_access"
keywords = ["arceos", "capabilities", "permission", "access-control"]
categories = ["os", "no-std"]

[dependencies]
bitflags = "2.6"
